### ISSUE TITLE
Paths should reflect `cpTrigger` value

### ISSUE THREAD

**Issue by lindseydiloreto** [danieltott/craft-sidebar-admin-links#1]
Very cool idea for a plugin, thanks for putting this together! Bumped into a little problem though...

It looks like the `/admin/` path is [hard-coded](https://github.com/danieltott/craft-sidebar-admin-links/blob/main/src/assetbundles/sidebaradminlinks/dist/js/sidebaradminlinks.js#L13-L31). For security purposes, many folks change this default value. Would you mind allowing the path to respect the value of [`cpTrigger`](https://craftcms.com/docs/3.x/config/config-settings.html#cptrigger) instead?

**Comment by RyanRoberts** [comment]
Came here to say the same 😆

**Comment by danieltott** [comment]
@lindseydiloreto Thank you for that! Ended up using `cpUrl()` to cover all the bases - should be working now in `1.1.0` 🎉

**Comment by lindseydiloreto** [comment]
Awesome, thanks for fixing that so quickly! 🍺
