### ISSUE TITLE
Craft 4 compatibility?

### ISSUE THREAD

**Issue by urgentdotagency** [danieltott/craft-sidebar-admin-links#3]
Big fan of this – any plans to update it for Craft 4?

**Comment by danieltott** [comment]
@urgentdotagency I'd love to - don't have the bandwidth any time this week but am open to pull requests! 😉

**Comment by danieltott** [comment]
For anyone looking to help - here are the upgrade docs: https://craftcms.com/docs/4.x/extend/updating-plugins.html

**Comment by danieltott** [comment]
@urgentdotagency good news - I finally upgraded this to Craft 4! https://github.com/danieltott/craft-sidebar-admin-links/releases
